### ISSUE TITLE
Add option for aarch64 to generate the URL

### ISSUE THREAD

**Issue by ossdev07** [mongodb-js/download-url#79]
Hi, 

I am working on the aarch64 architecture and trying to generate the URL to download MongoDB through this package.

But it is generating the URL of the X86 binary of MongoDB rather than of aarch64.

I looked into the package and can see in ```index.js``` there is no condition for the aarch64.

I would like to know, if you are interested we could put the architectural check for aarch64 in the ```index.js``` file so that it could generate the URL for aarch64.

**Comment by imlucas** [comment]
Fixed by #80 🙌
